#!/usr/bin/env bash
# scripts/export_chartnav_decks_to_desktop.sh — Phase 17 desktop
# demo delivery package exporter.
#
# What it does:
#   1. Recreates (or reuses) the operator's Desktop demo folder at
#      $CHARTNAV_DESKTOP_DIR (default
#      "/Users/jean-maxcharles/Desktop/chartnav decks").
#   2. Copies every Markdown source doc listed in the source-of-truth
#      contract (docs/chartnav-desktop-demo-delivery-package.md) to
#      its destination subfolder.
#   3. Generates the README.md at the Desktop folder root.
#   4. Generates three .command files in 08_Local_Demo_Launcher/
#      (START_CHARTNAV / STOP_CHARTNAV / RESET_DEMO_DATA) and marks
#      them executable.
#   5. Prints a summary tree.
#
# The Desktop folder is a *generated review package*, not source.
# The repo source under docs/ and scripts/ is the only source of
# truth. Desktop content is regenerated by running this script.
#
# Safety:
#   - Reads only from docs/, scripts/, and a known set of brand/text
#     assets. Does not read secrets, PHI, or backend code.
#   - Does not generate binary media (PNG/JPG/PDF/MP4/etc.).
#   - The reset .command file wraps scripts/reset_demo_state.sh,
#     which already refuses non-local DATABASE_URL values.
#   - The Desktop folder paths are listed in .gitignore so the
#     generated package is never committed.
#
# Usage:
#   bash scripts/export_chartnav_decks_to_desktop.sh
#
# Override the destination (e.g., for CI/dev users):
#   CHARTNAV_DESKTOP_DIR="$HOME/Desktop/chartnav decks" \
#     bash scripts/export_chartnav_decks_to_desktop.sh
#
# Exit codes:
#   0  export complete
#   1  required source file missing
#   2  filesystem error (mkdir / cp / chmod)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

DEFAULT_DESKTOP="/Users/jean-maxcharles/Desktop/chartnav decks"
DEST_DIR="${CHARTNAV_DESKTOP_DIR:-$DEFAULT_DESKTOP}"

# The repo path the START_CHARTNAV.command file should cd into on
# the operator's Mac. Override via CHARTNAV_REPO_DIR if needed.
DEFAULT_REPO_ON_MAC="/Users/jean-maxcharles/Desktop/ARCG/chartnav-platform"
REPO_ON_MAC="${CHARTNAV_REPO_DIR:-$DEFAULT_REPO_ON_MAC}"

echo "ChartNav desktop demo package export — fake-data demo only."
echo "  destination: $DEST_DIR"
echo "  repo-on-mac: $REPO_ON_MAC"
echo

# ---------------------------------------------------------------
# Source-of-truth contract — keep in sync with
#   docs/chartnav-desktop-demo-delivery-package.md
# Format: "<src relative to repo root>::<dest subfolder>"
# ---------------------------------------------------------------
MAPPING=(
  # 00_START_HERE — entry doc + commercial map / claims
  "docs/commercial/chartnav-deck-master-kit.md::00_START_HERE"
  "docs/commercial/chartnav-approved-claims-language.md::00_START_HERE"
  "docs/commercial/chartnav-commercial-readiness-map.md::00_START_HERE"

  # 01_Decks — the 17 deck Markdown source files (15 original
  # decks + Phase 17B buyer-demo / operator-demo split; the
  # original chartnav-demo-deck.md is now an index that routes
  # to one of the two)
  "docs/decks/chartnav-investor-pitch-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-sales-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-demo-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-buyer-demo-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-operator-demo-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-customer-pitch-deck-template.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-company-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-product-roadmap-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-brand-guidelines-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-educational-onboarding-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-financial-fundraising-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-marketing-plan-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-project-proposal-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-agency-partner-pitch-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-elevator-pitch-deck.md::01_Decks/Markdown_Source"
  "docs/decks/chartnav-long-sales-pitch-deck.md::01_Decks/Markdown_Source"

  # 02_One_Pagers — the one-page sales deck
  "docs/decks/chartnav-one-page-sales-deck.md::02_One_Pagers/Markdown_Source"

  # 03_Demo_Package — demo script + click path + shot list + ops guide
  "docs/demo/chartnav-clinical-workflow-demo-script.md::03_Demo_Package"
  "docs/demo/chartnav-demo-click-path.md::03_Demo_Package"
  "docs/demo/chartnav-video-clip-shot-list.md::03_Demo_Package"
  "docs/demo/chartnav-demo-operator-guide.md::03_Demo_Package"
  "docs/demo/chartnav-demo-environment.md::03_Demo_Package"

  # 04_Pilot_Sales — Phase 14 pilot packet + Phase 17 pilot handoff
  "docs/pilot/chartnav-pilot-readiness-checklist.md::04_Pilot_Sales"
  "docs/pilot/chartnav-pilot-deployment-guide.md::04_Pilot_Sales"
  "docs/pilot/chartnav-admin-onboarding-checklist.md::04_Pilot_Sales"
  "docs/pilot/chartnav-security-review-packet.md::04_Pilot_Sales"
  "docs/pilot/chartnav-support-runbook.md::04_Pilot_Sales"
  "docs/pilot/chartnav-demo-to-pilot-transition-plan.md::04_Pilot_Sales"
  "docs/pilot/chartnav-known-limitations-and-non-goals.md::04_Pilot_Sales"
  "docs/pilot/chartnav-pilot-success-metrics.md::04_Pilot_Sales"
  "docs/commercial/pilot/chartnav-pilot-handoff-checklist.md::04_Pilot_Sales"

  # 05_Objection_Handling — buyer objections doc
  "docs/commercial/objections/chartnav-buyer-objection-handling.md::05_Objection_Handling"

  # 06_Pricing_Packaging — pricing notes
  "docs/commercial/pricing/chartnav-pricing-packaging-notes.md::06_Pricing_Packaging"

  # 07_Website_Proof — Phase 16 contract + website shot list
  "docs/chartnav-website-proof-upgrade-conversion-layer.md::07_Website_Proof"
  "docs/website/chartnav-website-shot-list.md::07_Website_Proof"

  # 08_Local_Demo_Launcher — startup + troubleshooting (.command
  # files are generated, not copied)
  "docs/commercial/demo-package/chartnav-local-demo-startup-guide.md::08_Local_Demo_Launcher"
  "docs/commercial/demo-package/chartnav-local-demo-troubleshooting.md::08_Local_Demo_Launcher"

  # 09_Review_Checklists — demo review checklist
  "docs/commercial/demo-package/chartnav-demo-review-checklist.md::09_Review_Checklists"
)

SUBFOLDERS=(
  "00_START_HERE"
  "01_Decks"
  "01_Decks/Markdown_Source"
  "01_Decks/PPTX"
  "01_Decks/PDF"
  "02_One_Pagers"
  "02_One_Pagers/Markdown_Source"
  "02_One_Pagers/PPTX"
  "03_Demo_Package"
  "04_Pilot_Sales"
  "05_Objection_Handling"
  "06_Pricing_Packaging"
  "07_Website_Proof"
  "08_Local_Demo_Launcher"
  "09_Review_Checklists"
  "10_Presentation_Assets"
)

# ---------------------------------------------------------------
# 1. Validate every source file exists before we touch the Desktop.
# ---------------------------------------------------------------
echo "1. Validating source files…"
missing=0
for entry in "${MAPPING[@]}"; do
  src="${entry%%::*}"
  if [ ! -f "$src" ]; then
    echo "   MISSING: $src"
    missing=$((missing + 1))
  fi
done
if [ "$missing" -gt 0 ]; then
  echo "FAILED — $missing source file(s) missing. Aborting before touching Desktop."
  exit 1
fi
echo "   ok — all ${#MAPPING[@]} source file(s) present."
echo

# ---------------------------------------------------------------
# 2. Create the Desktop folder structure.
# ---------------------------------------------------------------
echo "2. Creating Desktop folder structure at:"
echo "   $DEST_DIR"
mkdir -p "$DEST_DIR"
for sub in "${SUBFOLDERS[@]}"; do
  mkdir -p "$DEST_DIR/$sub"
done
echo "   ok — ${#SUBFOLDERS[@]} subfolder(s) ensured."
echo

# ---------------------------------------------------------------
# 3. Copy source docs into their destination subfolders.
# ---------------------------------------------------------------
echo "3. Copying source docs…"
copied=0
for entry in "${MAPPING[@]}"; do
  src="${entry%%::*}"
  sub="${entry##*::}"
  dest="$DEST_DIR/$sub/$(basename "$src")"
  cp "$src" "$dest"
  copied=$((copied + 1))
done
echo "   ok — $copied file(s) copied."
echo

# ---------------------------------------------------------------
# 4. Generate the Desktop README.
# ---------------------------------------------------------------
echo "4. Generating Desktop README.md…"
README_PATH="$DEST_DIR/README.md"
cat > "$README_PATH" <<'README_EOF'
# ChartNav decks — Desktop demo delivery package

> Generated by `scripts/export_chartnav_decks_to_desktop.sh`.
> Do not edit files in this folder by hand — edit the source in the
> `chartnav-platform` repo and re-run the export script.

This folder is a presenter-ready review package. It contains every
commercial deck, every demo doc, every pilot doc, and every operator
script needed to run a ChartNav demo on the operator's Mac.

The local demo environment is **fake-data only** by construction.
No real PHI is ever loaded into local or staging environments. Real
PHI requires a controlled-pilot deployment with BAA + security
review (see `04_Pilot_Sales/`).

---

## Map of this folder

| Subfolder | What's in it |
|---|---|
| `00_START_HERE/` | Entry docs: master kit, approved claims language, commercial readiness map. |
| `01_Decks/` | 15 deck Markdown source files (investor, sales, demo, customer pitch, company, roadmap, brand, onboarding, fundraising, marketing, project proposal, agency partner, elevator, long sales, demo). |
| `02_One_Pagers/` | One-page sales deck. |
| `03_Demo_Package/` | Demo script (what to say), demo click path (what to click), video shot list, demo operator guide, demo environment doc. |
| `04_Pilot_Sales/` | Phase 14 pilot readiness packet (8 docs) + Phase 17 pilot handoff checklist. |
| `05_Objection_Handling/` | Buyer objection handling — 12 common objections with safe answers. |
| `06_Pricing_Packaging/` | Pricing + packaging notes (firm pilot fee, per-provider monthly hypothesis, what's validated vs. not). |
| `07_Website_Proof/` | Phase 16 landing-page contract + website shot list. |
| `08_Local_Demo_Launcher/` | START / STOP / RESET .command files + startup guide + troubleshooting. |
| `09_Review_Checklists/` | Demo review checklist (24h / 1h / 5min / during / after). |

---

## How to run a demo

1. Open `08_Local_Demo_Launcher/`.
2. Double-click `START_CHARTNAV.command`. A Terminal window opens,
   the local stack boots, and the browser opens to
   `http://localhost:5173/?demo=1`.
3. Walk the Guided Demo Mode 8-step path. Use the demo script in
   `03_Demo_Package/` for what to say and the click path for what
   to click.
4. After the demo, double-click `RESET_DEMO_DATA.command` to wipe
   the local SQLite dev DB and re-seed the fake demo data.
5. To stop the stack, double-click `STOP_CHARTNAV.command`.

If anything looks off, open
`08_Local_Demo_Launcher/chartnav-local-demo-troubleshooting.md`.

---

## Safety contract

- ChartNav is **provider-reviewed workflow support**. It does not
  diagnose, create orders, send referrals, bill, or message
  patients automatically.
- The local demo environment is **fake-data only**. The seeded
  patient is `Morgan Lee · PT-1001` in the `demo-eye-clinic` org.
- The `RESET_DEMO_DATA.command` file refuses to run against any
  `DATABASE_URL` that is not a local SQLite path.
- ChartNav is not HIPAA-certified, SOC 2-certified, or FDA-cleared.
  Covered entities and business associates implement HIPAA;
  ChartNav supports those obligations contractually via BAA.

---

## When to re-export

Whenever any source doc in the `chartnav-platform` repo updates,
re-run the export script from the repo root:

```
bash scripts/export_chartnav_decks_to_desktop.sh
```

The script is idempotent. Running it twice produces the same
Desktop folder state.

---

## Source of truth

The Markdown / shell content in this folder is a **copy** of the
corresponding files in the `chartnav-platform` repo. The repo is
the only source of truth. See
`docs/chartnav-desktop-demo-delivery-package.md` in the repo for
the full source-of-truth contract.
README_EOF
echo "   ok — README.md generated."
echo

# ---------------------------------------------------------------
# 5. Generate the three .command files.
# ---------------------------------------------------------------
echo "5. Generating .command files…"

LAUNCHER_DIR="$DEST_DIR/08_Local_Demo_Launcher"

START_CMD="$LAUNCHER_DIR/START_CHARTNAV.command"
STOP_CMD="$LAUNCHER_DIR/STOP_CHARTNAV.command"
RESET_CMD="$LAUNCHER_DIR/RESET_DEMO_DATA.command"

# START_CHARTNAV.command — boots local stack, opens browser.
cat > "$START_CMD" <<START_EOF
#!/usr/bin/env bash
# START_CHARTNAV.command — generated by
# scripts/export_chartnav_decks_to_desktop.sh
#
# Boots the ChartNav local stack and opens the browser to the
# Guided Demo Mode URL. Fake-data only by construction.

set -euo pipefail

REPO_DIR="${REPO_ON_MAC}"
DEMO_URL="http://localhost:5173/?demo=1"

echo "ChartNav local demo — fake-data only."
echo "  repo: \$REPO_DIR"
echo "  url:  \$DEMO_URL"
echo

if [ ! -d "\$REPO_DIR" ]; then
  echo "ERROR: repo not found at \$REPO_DIR"
  echo "       Edit this script or set CHARTNAV_REPO_DIR before re-exporting."
  read -r -p "Press return to close." _
  exit 1
fi

cd "\$REPO_DIR"

# Open the browser shortly after boot so the dev server has a
# moment to come up. Backgrounded so the foreground stays on
# 'make dev'.
( sleep 6 && open "\$DEMO_URL" ) &

if command -v make >/dev/null 2>&1 && [ -f Makefile ] \\
   && grep -Eq '^dev:' Makefile; then
  echo "Booting via 'make dev' …"
  make dev
else
  echo "ERROR: 'make dev' is not available in \$REPO_DIR"
  echo "       Open the repo manually and run the dev stack."
  read -r -p "Press return to close." _
  exit 1
fi
START_EOF

# STOP_CHARTNAV.command — kills processes on :8000 and :5173.
cat > "$STOP_CMD" <<'STOP_EOF'
#!/usr/bin/env bash
# STOP_CHARTNAV.command — generated by
# scripts/export_chartnav_decks_to_desktop.sh
#
# Stops the ChartNav local stack by terminating processes bound
# to the standard dev ports (:8000 API, :5173 frontend). Does not
# kill unrelated processes.

set -uo pipefail

echo "ChartNav local demo — stop."
echo

stop_port() {
  local port="$1"
  if ! command -v lsof >/dev/null 2>&1; then
    echo "  skip — lsof not available, cannot inspect :$port"
    return
  fi
  local pids
  pids="$(lsof -ti tcp:"$port" 2>/dev/null || true)"
  if [ -z "$pids" ]; then
    echo "  ok — nothing bound to :$port"
    return
  fi
  echo "  stopping pid(s) $pids on :$port (SIGTERM)…"
  # SIGTERM only — never SIGKILL unrelated processes.
  kill $pids 2>/dev/null || true
  sleep 1
  pids="$(lsof -ti tcp:"$port" 2>/dev/null || true)"
  if [ -n "$pids" ]; then
    echo "  warn — pid(s) $pids still bound to :$port; you may need to stop manually."
  else
    echo "  ok — :$port is free."
  fi
}

stop_port 8000
stop_port 5173

echo
echo "Done."
read -r -p "Press return to close." _
STOP_EOF

# RESET_DEMO_DATA.command — wraps scripts/reset_demo_state.sh.
cat > "$RESET_CMD" <<RESET_EOF
#!/usr/bin/env bash
# RESET_DEMO_DATA.command — generated by
# scripts/export_chartnav_decks_to_desktop.sh
#
# Wraps scripts/reset_demo_state.sh from the chartnav-platform
# repo. The underlying script refuses to run if DATABASE_URL
# points at anything other than the local SQLite default.

set -uo pipefail

REPO_DIR="${REPO_ON_MAC}"

echo "ChartNav demo reset — fake-data only."
echo "  repo: \$REPO_DIR"
echo

if [ ! -d "\$REPO_DIR" ]; then
  echo "ERROR: repo not found at \$REPO_DIR"
  echo "       Edit this script or set CHARTNAV_REPO_DIR before re-exporting."
  read -r -p "Press return to close." _
  exit 1
fi

cd "\$REPO_DIR"

if [ ! -f scripts/reset_demo_state.sh ]; then
  echo "ERROR: scripts/reset_demo_state.sh is missing in \$REPO_DIR"
  read -r -p "Press return to close." _
  exit 1
fi

bash scripts/reset_demo_state.sh
status=\$?
echo
if [ "\$status" -eq 0 ]; then
  echo "Reset complete. Hard-refresh your browser (Cmd-Shift-R)."
else
  echo "Reset exited with status \$status."
fi
read -r -p "Press return to close." _
exit \$status
RESET_EOF

chmod +x "$START_CMD" "$STOP_CMD" "$RESET_CMD"

echo "   ok — START_CHARTNAV.command, STOP_CHARTNAV.command, RESET_DEMO_DATA.command"
echo "        generated and marked executable."
echo

# ---------------------------------------------------------------
# 6. Copy presentation-assets docs into 10_Presentation_Assets/.
# ---------------------------------------------------------------
PRESENTATION_ASSETS_DIR="$DEST_DIR/10_Presentation_Assets"
PRESENTATION_DOCS_DIR="$REPO_ROOT/docs/presentations"
if [ -d "$PRESENTATION_DOCS_DIR" ]; then
  echo "6. Copying presentation-assets docs to 10_Presentation_Assets/…"
  copied_assets=0
  for f in "$PRESENTATION_DOCS_DIR"/*.md; do
    [ -f "$f" ] || continue
    cp "$f" "$PRESENTATION_ASSETS_DIR/$(basename "$f")"
    copied_assets=$((copied_assets + 1))
  done
  echo "   ok — $copied_assets asset doc(s) copied."
  echo
else
  echo "6. (no docs/presentations/ — skipping presentation-assets copy)"
  echo
fi

# ---------------------------------------------------------------
# 7. Optionally chain the Phase 17D presentation generator.
#    Skip when CHARTNAV_SKIP_PPTX=1 is set (useful for fast
#    Markdown-only refreshes).
# ---------------------------------------------------------------
if [ "${CHARTNAV_SKIP_PPTX:-0}" = "1" ]; then
  echo "7. (CHARTNAV_SKIP_PPTX=1 — skipping branded PPTX generation)"
  echo
elif command -v node >/dev/null 2>&1 && [ -f "$REPO_ROOT/tools/presentations/generateAll.js" ]; then
  echo "7. Generating branded PPTX presentations (Phase 17D)…"
  if [ ! -d "$REPO_ROOT/tools/presentations/node_modules" ]; then
    echo "   installing tools/presentations dependencies…"
    ( cd "$REPO_ROOT/tools/presentations" && npm install --no-audit --no-fund >/dev/null 2>&1 )
  fi
  CHARTNAV_DESKTOP_DIR="$DEST_DIR" node "$REPO_ROOT/tools/presentations/generateAll.js" \
    | sed 's|^|   |'
  echo
else
  echo "7. (Node / generator not available — skipping branded PPTX generation)"
  echo
fi

# ---------------------------------------------------------------
# 8. Print summary tree.
# ---------------------------------------------------------------
echo "8. Summary tree (depth 2):"
if command -v find >/dev/null 2>&1; then
  ( cd "$DEST_DIR" && find . -maxdepth 2 -mindepth 1 \
      -not -path '*/.*' -print | sort | sed 's|^\./|  |' )
fi
echo

echo "Export complete."
echo "  $copied source files copied · 1 README + 3 .command files generated."
echo "  Branded PPTX presentations generated under 01_Decks/PPTX/ and"
echo "  02_One_Pagers/PPTX/ (Phase 17D)."
echo "  Source of truth lives in the chartnav-platform repo;"
echo "  the Desktop folder is a regenerated review package."
