"""Consult letter rendering + delivery dispatcher.

Spec: docs/chartnav/closure/PHASE_B_Referring_Provider_Communication.md

What this module does:
  - validate the NPI-10 of a referring-provider record (CMS Luhn);
  - render a plain-text body for a consult letter from a signed
    encounter + note version + referring-provider record;
  - wrap that body in a minimal valid PDF using the same writer
    `app.services.handoff_export.render_pdf_bytes` already used for
    the Phase A PM/RCM handoff bundle (no heavy WeasyPrint dep);
  - provide a single `dispatch_delivery` entry point that records
    the channel choice deterministically — "download" produces a
    real PDF, "email" + "fax_stub" record intent only.

What this module does NOT do (truth limitations §9 of the spec):
  - it does not transmit bytes over fax;
  - it does not call SMTP unless the operator wires real SMTP
    credentials in a future Phase C wedge — Phase B records intent;
  - it does not POST a FHIR DocumentReference; the
    `post_document_reference` hook is a no-op stub guarded by mode
    and exposed for Phase C wiring.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from app.services.handoff_export import render_pdf_bytes


# ---------- NPI-10 validation -----------------------------------------

def is_valid_npi10(npi: str) -> bool:
    """CMS LUHN_10 check digit validation for a 10-digit NPI.

    Per the CMS NPPES specification: the prefix '80840' is appended
    in front of the first 9 digits, every second digit from the
    right is doubled, double-digit results are summed, and the total
    plus the 10th NPI digit must be divisible by 10.
    """
    if not isinstance(npi, str) or not npi.isdigit() or len(npi) != 10:
        return False
    digits = [int(c) for c in "80840" + npi[:9]]
    total = 0
    for i, d in enumerate(reversed(digits)):
        # double every other digit starting from the rightmost
        if i % 2 == 0:
            d *= 2
            if d > 9:
                d -= 9
        total += d
    check_digit = int(npi[9])
    return (total + check_digit) % 10 == 0


# ---------- Letter body renderer --------------------------------------

def render_letter_body(
    *,
    encounter: dict,
    note_text: str,
    referring_provider: dict,
    org_name: str,
    sent_on: str | None = None,
) -> str:
    """Plain-text consult letter body. The four variable slots
    referenced in spec §6 are: referring-provider salutation,
    patient identifier, encounter-date, and the note body."""
    sent_on = sent_on or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    rp_name = referring_provider.get("name") or "Referring Provider"
    rp_practice = referring_provider.get("practice") or ""
    salutation_org = f", {rp_practice}" if rp_practice else ""
    lines: list[str] = []
    lines.append(f"{org_name}")
    lines.append(f"Consult letter — {sent_on}")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"To: {rp_name}{salutation_org}")
    lines.append("")
    lines.append(
        f"Re: {encounter.get('patient_name') or encounter.get('patient_identifier', '')}"
    )
    lines.append(f"MRN: {encounter.get('patient_identifier', '')}")
    lines.append(
        f"Date of service: {encounter.get('completed_at') or encounter.get('scheduled_at') or sent_on}"
    )
    lines.append(
        f"Provider: {encounter.get('provider_name', '')}"
    )
    lines.append("")
    lines.append("Dear " + rp_name + ",")
    lines.append("")
    lines.append(
        "Thank you for the referral. Below is the assessment and plan "
        "from today's visit."
    )
    lines.append("")
    lines.append("--- Assessment and plan ---")
    lines.append(note_text or "(note body not supplied)")
    lines.append("")
    lines.append("This letter is generated by ChartNav from the signed")
    lines.append("encounter note. ChartNav does not transmit claims and")
    lines.append("does not replace the signed note in the EHR of record.")
    lines.append("")
    lines.append("Sincerely,")
    lines.append(encounter.get("provider_name") or "")
    return "\n".join(lines)


def render_letter_pdf(
    *,
    encounter: dict,
    note_text: str,
    referring_provider: dict,
    org_name: str,
) -> bytes:
    """End-to-end: render the letter body and wrap it in a minimal PDF."""
    body = render_letter_body(
        encounter=encounter,
        note_text=note_text,
        referring_provider=referring_provider,
        org_name=org_name,
    )
    return render_pdf_bytes(body)


# ---------- Delivery dispatcher ---------------------------------------

VALID_CHANNELS = ("download", "email", "fax_stub")


def dispatch_delivery(
    *,
    channel: str,
    referring_provider: dict,
) -> dict[str, Any]:
    """Record the delivery intent for a channel.

    Returns a structured result the route layer persists on the
    `consult_letters` row. The result is deterministic — no I/O is
    performed against external SMTP / fax systems in Phase B.
    """
    if channel not in VALID_CHANNELS:
        raise ValueError(f"unknown_delivery_channel: {channel}")
    if channel == "download":
        return {
            "delivery_status": "rendered",
            "delivered_via": "download",
            "sent_at": None,
            "advisory": (
                "Download channel selected. The PDF is available "
                "to authorized roles via GET /consult-letters/{id}/pdf."
            ),
        }
    if channel == "email":
        # Phase B: record intent only. Real SMTP wiring is Phase C.
        if not referring_provider.get("email"):
            raise ValueError("referring_provider_missing_email")
        return {
            "delivery_status": "stub_logged",
            "delivered_via": "email",
            "sent_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "advisory": (
                "Email delivery is recorded as intent only in Phase B. "
                "ChartNav does not operate a shared outbound relay; "
                "operator SMTP wiring is required and lands in Phase C."
            ),
        }
    # fax_stub
    return {
        "delivery_status": "stub_logged",
        "delivered_via": "fax_stub",
        "sent_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "advisory": (
            "Fax queued (stub — no transmission in pilot). A real fax "
            "vendor (sFax / Documo / Phaxio) is wired in Phase C."
        ),
    }


# ---------- FHIR DocumentReference hook (Phase C placeholder) ----------

def post_document_reference(
    *,
    consult_letter: dict,
    deployment_mode: str,
) -> dict[str, Any]:
    """Spec §5: only called when mode is `integrated_writethrough`.

    In any other mode the call is explicitly skipped and the reason
    is recorded so audit log entries are honest. We do NOT implement
    a live FHIR POST in Phase B — that's Phase C wiring.
    """
    if deployment_mode != "integrated_writethrough":
        return {
            "fhir_posted": False,
            "skipped_reason": (
                f"deployment_mode={deployment_mode} is not "
                "integrated_writethrough; FHIR DocumentReference "
                "POST is intentionally skipped per spec §9."
            ),
        }
    # Phase C will plug a real FHIR client here. For now we record
    # the intent and surface a clear skip-reason so no caller can
    # mistakenly believe the POST occurred.
    return {
        "fhir_posted": False,
        "skipped_reason": (
            "integrated_writethrough mode detected, but the FHIR "
            "DocumentReference POST is not wired in Phase B. "
            "Wiring lands in Phase C."
        ),
    }
